version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install databricks-cli
  build:
    commands:
      - echo "Starting Databricks Deployment..."
      - export DATABRICKS_HOST="https://dbc-19dd5697-db5b.cloud.databricks.com"
      - export DATABRICKS_TOKEN="dapied254a643e30617a3526aa324911c84a"
      - echo "Deleting existing script..."
      - databricks workspace delete /Workspace/path || true
      - echo "Importing new script..."
      - databricks workspace import script.py /Workspace/path --language PYTHON --overwrite
      - echo "Deployment Complete!"
