version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install databricks-cli
  build:
    commands:
      - echo "Starting Databricks Deployment..."
      - export DATABRICKS_HOST="https://dbc-5f99fc48-0975.cloud.databricks.com"
      - export DATABRICKS_TOKEN="dapie6e44bd23367fa14cb92cc95cf048cb"
      - echo "Deleting existing script..."
      - databricks workspace delete /Workspace/path || true
      - echo "Importing new script..."
      - databricks workspace import script.py /Workspace/path --language PYTHON --overwrite
      - echo "Deployment Complete!"
